<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Welcome_model extends CI_Model
{

    public $table = 'obj3_sam_rec';
    public $id = '';
    public $order = '';

    function __construct()
    {
        parent::__construct();
        // $this->main_db = $this->load->database('main_db', TRUE);       
        $this->load->database();
    }

    function get_by_id()
    {
        $this->db->select('*');
        return $this->db->get($this->table)->row();
                
    }

    // public function get_deleted_records($main_table, $lab_table, $column)
    // {
    //     // Get data from the client/lab database
    //     $this->db->select($column);
    //     $lab_query = $this->db->get($lab_table);
    //     $lab_data = array_column($lab_query->result_array(), $column);

    //     $lab = $this->session->userdata('lab');
    //     // Get data from the main database
    //     $this->main_db->select($column);
    //     $this->main_db->where('lab', $lab);
    //     $main_query = $this->main_db->get($main_table);
    //     $main_data = $main_query->result_array();

    //     // Find records in main database not present in lab database
    //     $deleted_records = array_filter($main_data, function($record) use ($lab_data, $column) {
    //         return !in_array($record[$column], $lab_data);
    //     });

    //     return $deleted_records;
    // }


    // public function delete_records($main_table, $deleted_records, $column)
    // {
    //     $lab = $this->session->userdata('lab');
    //     foreach ($deleted_records as $record) {
    //         $this->main_db->where('lab', $lab);
    //         $this->main_db->delete($main_table, array($column => $record[$column]));        }
    // }    

    // datatables
    function get_sum() {
        $query = $this->db->query('SELECT "Objective 3" AS item, COUNT(*) AS val
        FROM obj3_sam_rec
        WHERE lab = "'.$this->session->userdata('lab').'" 
                AND flag = 0 
        UNION ALL
        SELECT "Objective 2A" AS item, COUNT(*) AS val
        FROM obj2a_receipt
        WHERE lab = "'.$this->session->userdata('lab').'" 
                AND flag = 0 
        UNION ALL
        SELECT "Objective 2B" AS item, COUNT(*) AS val
        FROM obj2b_receipt
        WHERE lab = "'.$this->session->userdata('lab').'" 
        AND flag = 0 
        UNION ALL
        SELECT "NHMRC" AS item, COUNT(*) AS val
        FROM nhmrc_receipt
        WHERE lab = "'.$this->session->userdata('lab').'" 
                AND flag = 0 
        ');
        $result = $query->result();
        
        return $result;
    }

    function get_subsum() {
        $query = $this->db->query('SELECT "O3", 
        CASE
            WHEN a.id_type IN (1,2,3,5) THEN "Human Blood"
            WHEN a.id_type = 4 THEN "Human Feces"
            ELSE "Unidentify"
        END AS "type",
        COUNT(*) AS val
        FROM obj3_sam_rec a
        LEFT JOIN ref_sampletype b ON a.id_type=b.id_sampletype
        WHERE a.lab = "'.$this->session->userdata('lab').'" 
                AND a.flag = 0 
        GROUP BY type
        UNION ALL
        SELECT "O2A", a.sample_type AS "type", COUNT(*) AS val
        FROM obj2a_receipt a
        WHERE a.lab = "'.$this->session->userdata('lab').'" 
                AND a.flag = 0 
        GROUP BY a.sample_type
        UNION ALL
        SELECT "O2B", b.sampletype AS "type", COUNT(*) AS val
        FROM obj2b_receipt a
        LEFT JOIN ref_sampletype b ON a.id_type2b=b.id_sampletype
        WHERE a.lab = "'.$this->session->userdata('lab').'" 
                AND a.flag = 0 
        GROUP BY a.id_type2b             
        UNION ALL
        SELECT "O2B", b.sampletype AS "type", COUNT(*) AS val
        FROM nhmrc_receipt a
        LEFT JOIN ref_sampletype b ON a.id_type2b=b.id_sampletype
        WHERE a.lab = "'.$this->session->userdata('lab').'" 
                AND a.flag = 0 
        GROUP BY a.id_type2b             
        ');
        $result = $query->result();
        
        return $result;
    }
    


}

/* End of file User_model.php */
/* Location: ./application/models/User_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-10-04 06:32:22 */
/* http://harviacode.com */